# Test your FastAPI endpoints

GET http://127.0.0.1:8000/
Accept: application/json

###

GET http://127.0.0.1:8000/hello/User
Accept: application/json

###

# 获取当前时间（多种格式）
GET http://127.0.0.1:8000/api/get_time
Accept: application/json

###

# 获取武汉天气
GET http://127.0.0.1:8000/api/weather
Accept: application/json

###

# 获取指定城市天气
GET http://127.0.0.1:8000/api/weather?city=北京
Accept: application/json

###
